/**
*
*  Copyright 2007 Sohu.com Inc. All rights reserved.
*  搜狐公司
*  @author jadyyang@sohu.com
*  date: 2008-01-11
**/
var Prototype={Version:'1.5.0_rc0',ScriptFragment:'(?:<script.*?>)((\n|\r|.)*?)(?:<\/script>)',emptyFunction:function(){},K:function(x){return x;}};var Class={create:function(){return function(){this.initialize.apply(this,arguments);};}};var Abstract=new Object();Object.extend=function(destination,source){for(var property in source){destination[property]=source[property];}
return destination;};Object.inspect=function(object){try{if(object==undefined){return'undefined';}
if(object==null){return'null';}
return object.inspect?object.inspect():object.toString();}catch(e){if(e instanceof RangeError){return'...';}
throw e;}};Function.prototype.bind=function(){var __method=this,args=$A(arguments),object=args.shift();return function(){return __method.apply(object,args.concat($A(arguments)));};};Function.prototype.bindAsEventListener=function(object){var __method=this;return function(event){return __method.call(object,event||window.event);};};Object.extend(Number.prototype,{toColorPart:function(){var digits=this.toString(16);if(this<16){return'0'+digits;}
return digits;},succ:function(){return this+1;},times:function(iterator){$R(0,this,true).each(iterator);return this;}});var Try={these:function(){var returnValue;for(var i=0;i<arguments.length;i++){var lambda=arguments[i];try{returnValue=lambda();break;}catch(e){}}
return returnValue;}};var PeriodicalExecuter=Class.create();PeriodicalExecuter.prototype={initialize:function(callback,frequency){this.callback=callback;this.frequency=frequency;this.currentlyExecuting=false;this.registerCallback();},registerCallback:function(){setInterval(this.onTimerEvent.bind(this),this.frequency*1000);},onTimerEvent:function(){if(!this.currentlyExecuting){try{this.currentlyExecuting=true;this.callback();}finally{this.currentlyExecuting=false;}}}};Object.extend(String.prototype,{gsub:function(pattern,replacement){var result='',source=this,match;replacement=arguments.callee.prepareReplacement(replacement);while(source.length>0){if(source.match(pattern)){match=source.match(pattern);result+=source.slice(0,match.index);result+=(replacement(match)||'').toString();source=source.slice(match.index+match[0].length);}else{result+=source;source='';}}
return result;},sub:function(pattern,replacement,count){replacement=this.gsub.prepareReplacement(replacement);count=count===undefined?1:count;return this.gsub(pattern,function(match){if(--count<0){return match[0];}
return replacement(match);});},scan:function(pattern,iterator){this.gsub(pattern,iterator);return this;},truncate:function(length,truncation){length=length||30;truncation=truncation===undefined?'...':truncation;return this.length>length?this.slice(0,length-truncation.length)+truncation:this;},strip:function(){return this.replace(/^\s+/,'').replace(/\s+$/,'');},stripTags:function(){return this.replace(/<\/?[^>]+>/gi,'');},stripScripts:function(){return this.replace(new RegExp(Prototype.ScriptFragment,'img'),'');},extractScripts:function(){var matchAll=new RegExp(Prototype.ScriptFragment,'img');var matchOne=new RegExp(Prototype.ScriptFragment,'im');return(this.match(matchAll)||[]).map(function(scriptTag){return(scriptTag.match(matchOne)||['',''])[1];});},evalScripts:function(){return this.extractScripts().map(function(script){return eval(script);});},escapeHTML:function(){var div=document.createElement('div');var text=document.createTextNode(this);div.appendChild(text);return div.innerHTML;},unescapeHTML:function(){var div=document.createElement('div');div.innerHTML=this.stripTags();return div.childNodes[0]?div.childNodes[0].nodeValue:'';},convertTextToHTML:function(){return(this.replace(/\&/g,"&").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/\r\n|\n|\r/g,"<br \/>").replace(/  /g,"&nbsp; "));},convertHTMLToText:function(){return(this.replace(/(\s*(\r\n|\n|\r)\s*)/g,"").replace(/&/g,"&").replace(/</g,"<").replace(/>/g,">").replace(/<br\s*\/?>/ig,"\r\n").replace(/\&nbsp;/g," "));},trim:function(){return(this.replace(/(^\s*)|(\s*$)/g,""));},toQueryParams:function(){var pairs=this.match(/^\??(.*)$/)[1].split('&');return pairs.inject({},function(params,pairString){var pair=pairString.split('=');params[pair[0]]=pair[1];return params;});},toArray:function(){return this.split('');},camelize:function(){var oStringList=this.split('-');if(oStringList.length==1){return oStringList[0];}
var camelizedString=this.indexOf('-')==0?oStringList[0].charAt(0).toUpperCase()+oStringList[0].substring(1):oStringList[0];for(var i=1,len=oStringList.length;i<len;i++){var s=oStringList[i];camelizedString+=s.charAt(0).toUpperCase()+s.substring(1);}
return camelizedString;},underscore:function(){return this.gsub(/::/,'/').gsub(/([A-Z]+)([A-Z][a-z])/,'#{1}_#{2}').gsub(/([a-z\d])([A-Z])/,'#{1}_#{2}').gsub(/-/,'_').toLowerCase();},dasherize:function(){return this.gsub(/_/,'-');},inspect:function(){return"'"+this.replace(/\\/g,'\\\\').replace(/'/g,'\\\'')+"'";}});String.prototype.gsub.prepareReplacement=function(replacement){if(typeof replacement=='function'){return replacement;}
var template=new Template(replacement);return function(match){return template.evaluate(match);};};String.prototype.parseQuery=String.prototype.toQueryParams;var Template=Class.create();Template.Pattern=/(^|.|\r|\n)(#\{(.*?)\})/;Template.prototype={initialize:function(template,pattern){this.template=template.toString();this.pattern=pattern||Template.Pattern;},evaluate:function(object){return this.template.gsub(this.pattern,function(match){var before=match[1];if(before=='\\'){return match[2];}
return before+(object[match[3]]||'').toString();});}};var $break=new Object();var $continue=new Object();var Enumerable={each:function(iterator){var index=0;try{this._each(function(value){try{iterator(value,index++);}catch(e){if(e!=$continue){throw e;}}});}catch(e){if(e!=$break){throw e;}}},all:function(iterator){var result=true;this.each(function(value,index){result=result&&!!(iterator||Prototype.K)(value,index);if(!result){throw $break;}});return result;},any:function(iterator){var result=false;this.each(function(value,index){if(!!(iterator||Prototype.K)(value,index)){result=!!(iterator||Prototype.K)(value,index);throw $break;}});return result;},collect:function(iterator){var results=[];this.each(function(value,index){results.push(iterator(value,index));});return results;},detect:function(iterator){var result;this.each(function(value,index){if(iterator(value,index)){result=value;throw $break;}});return result;},findAll:function(iterator){var results=[];this.each(function(value,index){if(iterator(value,index)){results.push(value);}});return results;},grep:function(pattern,iterator){var results=[];this.each(function(value,index){var stringValue=value.toString();if(stringValue.match(pattern)){results.push((iterator||Prototype.K)(value,index));}});return results;},include:function(object){var found=false;this.each(function(value){if(value==object){found=true;throw $break;}});return found;},inject:function(memo,iterator){this.each(function(value,index){memo=iterator(memo,value,index);});return memo;},invoke:function(method){var args=$A(arguments).slice(1);return this.collect(function(value){return value[method].apply(value,args);});},max:function(iterator){var result;this.each(function(value,index){value=(iterator||Prototype.K)(value,index);if(result==undefined||value>=result){result=value;}});return result;},min:function(iterator){var result;this.each(function(value,index){value=(iterator||Prototype.K)(value,index);if(result==undefined||value<result){result=value;}});return result;},partition:function(iterator){var trues=[],falses=[];this.each(function(value,index){((iterator||Prototype.K)(value,index)?trues:falses).push(value);});return[trues,falses];},pluck:function(property){var results=[];this.each(function(value,index){results.push(value[property]);});return results;},reject:function(iterator){var results=[];this.each(function(value,index){if(!iterator(value,index)){results.push(value);}});return results;},sortBy:function(iterator){return this.collect(function(value,index){return{value:value,criteria:iterator(value,index)};}).sort(function(left,right){var a=left.criteria,b=right.criteria;return a<b?-1:a>b?1:0;}).pluck('value');},toArray:function(){return this.collect(Prototype.K);},zip:function(){var iterator=Prototype.K,args=$A(arguments);if(typeof args.last()=='function'){iterator=args.pop();}
var collections=[this].concat(args).map($A);return this.map(function(value,index){return iterator(collections.pluck(index));});},inspect:function(){return'#<Enumerable:'+this.toArray().inspect()+'>';}};Object.extend(Enumerable,{map:Enumerable.collect,find:Enumerable.detect,select:Enumerable.findAll,member:Enumerable.include,entries:Enumerable.toArray});Array.from=function(iterable){if(!iterable){return[];}
if(iterable.toArray){return iterable.toArray();}else{var results=[];var l=iterable.length;for(var i=0;i<l;i++){results.push(iterable[i]);}
return results;}};var $A=Array.from;Object.extend(Array.prototype,Enumerable);if(!Array.prototype._reverse){Array.prototype._reverse=Array.prototype.reverse;}
Object.extend(Array.prototype,{_each:function(iterator){var l=this.length;for(var i=0;i<l;i++){iterator(this[i]);}},clear:function(){this.length=0;return this;},first:function(){return this[0];},last:function(){return this[this.length-1];},compact:function(){return this.select(function(value){return value!=undefined||value!=null;});},flatten:function(){return this.inject([],function(array,value){return array.concat(value&&value.constructor==Array?value.flatten():[value]);});},without:function(){var values=$A(arguments);return this.select(function(value){return!values.include(value);});},indexOf:function(object){for(var i=0;i<this.length;i++){if(this[i]==object){return i;}}
return-1;},reverse:function(inline){return(inline!==false?this:this.toArray())._reverse();},inspect:function(){return'['+this.map(Object.inspect).join(', ')+']';}});var Hash={_each:function(iterator){for(var key in this){var value=this[key];if(typeof value=='function'){continue;}
var pair=[key,value];pair.key=key;pair.value=value;iterator(pair);}},keys:function(){return this.pluck('key');},values:function(){return this.pluck('value');},merge:function(hash){return $H(hash).inject($H(this),function(mergedHash,pair){mergedHash[pair.key]=pair.value;return mergedHash;});},toQueryString:function(){return this.map(function(pair){return pair.map(encodeURIComponent).join('=');}).join('&');},inspect:function(){return'#<Hash:{'+this.map(function(pair){return pair.map(Object.inspect).join(': ');}).join(', ')+'}>';}};function $H(object){var hash=Object.extend({},object||{});Object.extend(hash,Enumerable);Object.extend(hash,Hash);return hash;}
ObjectRange=Class.create();Object.extend(ObjectRange.prototype,Enumerable);Object.extend(ObjectRange.prototype,{initialize:function(start,end,exclusive){this.start=start;this.end=end;this.exclusive=exclusive;},_each:function(iterator){var value=this.start;do{iterator(value);value=value.succ();}while(this.include(value));},include:function(value){if(value<this.start){return false;}
if(this.exclusive){return value<this.end;}
return value<=this.end;}});var $R=function(start,end,exclusive){return new ObjectRange(start,end,exclusive);};var Ajax={getTransport:function(){return Try.these(function(){return new XMLHttpRequest();},function(){return new ActiveXObject('Msxml2.XMLHTTP');},function(){return new ActiveXObject('Microsoft.XMLHTTP');})||false;},activeRequestCount:0};Ajax.Responders={responders:[],_each:function(iterator){this.responders._each(iterator);},register:function(responderToAdd){if(!this.include(responderToAdd)){this.responders.push(responderToAdd);}},unregister:function(responderToRemove){this.responders=this.responders.without(responderToRemove);},dispatch:function(callback,request,transport,json){this.each(function(responder){if(responder[callback]&&typeof responder[callback]=='function'){try{responder[callback].apply(responder,[request,transport,json]);}catch(e){}}});}};Object.extend(Ajax.Responders,Enumerable);Ajax.Responders.register({onCreate:function(){Ajax.activeRequestCount++;},onComplete:function(){Ajax.activeRequestCount--;}});Ajax.Base=function(){};Ajax.Base.prototype={setOptions:function(options){this.options={method:'post',asynchronous:true,contentType:'application/x-www-form-urlencoded',parameters:''};Object.extend(this.options,options||{});},responseIsSuccess:function(){return this.transport.status==undefined||this.transport.status==0||(this.transport.status>=200&&this.transport.status<300);},responseIsFailure:function(){return!this.responseIsSuccess();}};Ajax.Request=Class.create();Ajax.Request.Events=['Uninitialized','Loading','Loaded','Interactive','Complete'];Ajax.Request.prototype=Object.extend(new Ajax.Base(),{initialize:function(url,options){this.transport=Ajax.getTransport();this.setOptions(options);this.request(url);},request:function(url){var parameters=this.options.parameters||'';if(parameters.length>0){parameters+='&_=';}
try{this.url=url;if(this.options.method=='get'&&parameters.length>0){this.url+=(this.url.match(/\?/)?'&':'?')+parameters;}
Ajax.Responders.dispatch('onCreate',this,this.transport);this.transport.open(this.options.method,this.url,this.options.asynchronous);if(this.options.asynchronous){this.transport.onreadystatechange=this.onStateChange.bind(this);setTimeout((function(){this.respondToReadyState(1);}).bind(this),10);}
this.setRequestHeaders();var body=this.options.postBody?this.options.postBody:parameters;this.transport.send(this.options.method=='post'?body:null);}catch(e){this.dispatchException(e);}},setRequestHeaders:function(){var requestHeaders=['X-Requested-With','XMLHttpRequest','X-Prototype-Version',Prototype.Version,'Accept','text/javascript, text/html, application/xml, text/xml, */*'];if(this.options.method=='post'){requestHeaders.push('Content-type',this.options.contentType);if(this.transport.overrideMimeType){requestHeaders.push('Connection','close');}}
if(this.options.requestHeaders){requestHeaders.push.apply(requestHeaders,this.options.requestHeaders);}
for(var i=0;i<requestHeaders.length;i+=2){this.transport.setRequestHeader(requestHeaders[i],requestHeaders[i+1]);}},onStateChange:function(){var readyState=this.transport.readyState;if(readyState!=1){this.respondToReadyState(this.transport.readyState);}},header:function(name){try{return this.transport.getResponseHeader(name);}catch(e){}},evalJSON:function(){try{return eval('('+this.header('X-JSON')+')');}catch(e){}},evalResponse:function(){try{return eval(this.transport.responseText);}catch(e){this.dispatchException(e);}},respondToReadyState:function(readyState){var event=Ajax.Request.Events[readyState];var transport=this.transport,json=this.evalJSON();var data=this.options.data;if(event=='Complete'){(this.options['on'+this.transport.status]||this.options['on'+(this.responseIsSuccess()?'Success':'Failure')]||Prototype.emptyFunction)(transport,json,data);if((this.header('Content-type')||'').match(/^text\/javascript/i)){this.evalResponse();}}
(this.options['on'+event]||Prototype.emptyFunction)(transport,json,data);Ajax.Responders.dispatch('on'+event,this,transport,json);if(event=='Complete'){this.transport.onreadystatechange=Prototype.emptyFunction;}},dispatchException:function(exception){(this.options.onException||Prototype.emptyFunction)(this,exception);Ajax.Responders.dispatch('onException',this,exception);}});Ajax.Updater=Class.create();Object.extend(Object.extend(Ajax.Updater.prototype,Ajax.Request.prototype),{initialize:function(container,url,options){this.containers={success:container.success?$(container.success):$(container),failure:container.failure?$(container.failure):(container.success?null:$(container))};this.transport=Ajax.getTransport();this.setOptions(options);var onComplete=this.options.onComplete||Prototype.emptyFunction;this.options.onComplete=(function(transport,object){this.updateContent();onComplete(transport,object);}).bind(this);this.request(url);},updateContent:function(){var receiver=this.responseIsSuccess()?this.containers.success:this.containers.failure;var response=this.transport.responseText;if(!this.options.evalScripts){response=response.stripScripts();}
if(receiver){if(this.options.insertion){new this.options.insertion(receiver,response);}else{Element.update(receiver,response);}}
if(this.responseIsSuccess()){if(this.onComplete){setTimeout(this.onComplete.bind(this),10);}}}});Ajax.PeriodicalUpdater=Class.create();Ajax.PeriodicalUpdater.prototype=Object.extend(new Ajax.Base(),{initialize:function(container,url,options){this.setOptions(options);this.onComplete=this.options.onComplete;this.frequency=(this.options.frequency||2);this.decay=(this.options.decay||1);this.updater={};this.container=container;this.url=url;this.start();},start:function(){this.options.onComplete=this.updateComplete.bind(this);this.onTimerEvent();},stop:function(){this.updater.onComplete=undefined;clearTimeout(this.timer);(this.onComplete||Prototype.emptyFunction).apply(this,arguments);},updateComplete:function(request){if(this.options.decay){this.decay=(request.responseText==this.lastText?this.decay*this.options.decay:1);this.lastText=request.responseText;}
this.timer=setTimeout(this.onTimerEvent.bind(this),this.decay*this.frequency*1000);},onTimerEvent:function(){this.updater=new Ajax.Updater(this.container,this.url,this.options);}});function $(){var results=[],element;for(var i=0;i<arguments.length;i++){element=arguments[i];if(typeof element=='string'){element=document.getElementById(element);}
try{results.push(Element.extend(element));}catch(e){results.push(element);}}
return results.length<2?results[0]:results;}
document.getElementsByClassName=function(className,parentElement,tagName){var children=($(parentElement)||document.body).getElementsByTagName(tagName||'*');return $A(children).inject([],function(elements,child){if(child.className.match(new RegExp("(^|\\s)"+className+"(\\s|$)"))){elements.push(Element.extend(child));}
return elements;});};if(!window.Element){var Element=new Object();}
Element.extend=function(element){if(!element){return null;}
if(_nativeExtensions){return element;}
if(!element._extended&&element.tagName&&element!=window){var methods=Element.Methods,cache=Element.extend.cache;for(property in methods){var value=methods[property];if(typeof value=='function'){element[property]=cache.findOrStore(value);}}}
element._extended=true;return element;};Element.extend.cache={findOrStore:function(value){this[value]=this[value]||function(){return value.apply(null,[this].concat($A(arguments)));};return this[value];}};Element.Methods={visible:function(element){return $(element).style.display!='none';},toggle:function(){for(var i=0;i<arguments.length;i++){var element=$(arguments[i]);Element[Element.visible(element)?'hide':'show'](element);}},hide:function(){for(var i=0;i<arguments.length;i++){var element=$(arguments[i]);element.style.display='none';}},show:function(){for(var i=0;i<arguments.length;i++){var element=$(arguments[i]);element.style.display='';}},remove:function(element){element=$(element);element.parentNode.removeChild(element);},update:function(element,html){$(element).innerHTML=html.stripScripts();setTimeout(function(){html.evalScripts();},10);},replace:function(element,html){element=$(element);if(element.outerHTML){element.outerHTML=html.stripScripts();}else{var range=element.ownerDocument.createRange();range.selectNodeContents(element);element.parentNode.replaceChild(range.createContextualFragment(html.stripScripts()),element);}
setTimeout(function(){html.evalScripts();},10);},getWidth:function(element){element=$(element);return element.offsetWidth;},getHeight:function(element){element=$(element);return element.offsetHeight;},classNames:function(element){return new Element.ClassNames(element);},hasClassName:function(element,className){if(!(element=$(element))){return;}
return Element.classNames(element).include(className);},addClassName:function(element,className){if(!(element=$(element))){return;}
return Element.classNames(element).add(className);},removeClassName:function(element,className){if(!(element=$(element))){return;}
return Element.classNames(element).remove(className);},swapClassName:function(element){element=$(element);for(var i=1;i<arguments.length;i++){if(element.className==arguments[i]){element.className=(i==arguments.length-1?arguments[1]:arguments[i+1]);break;}}},getParentElementByTagName:function(element,tagName){element=$(element);while(element.tagName!=tagName){element=element.parentNode;}
return element;},getChildElementByTagName:function(element,tagName){element=$(element);var ln=element.childNodes.length;var arr=[];for(var i=0;i<ln;i++){if(element.childNodes[i].nodeName==tagName){arr.push(element.childNodes[i]);}}
return arr;},getParentElementByClassName:function(element,_className){element=$(element);while(element.className!=_className){element=element.parentNode;}
return element;},getChildValueByTagName:function(element,tagName){element=$(element);var arr=$A(element.getElementsByTagName(tagName)).map(function(c){return(c.firstChild)?((c.firstChild.nodetype!=1)?c.firstChild.data:null):'';});return arr;},cleanWhitespace:function(element){element=$(element);for(var i=0;i<element.childNodes.length;i++){var node=element.childNodes[i];if(node.nodeType==3&&(!(/\S/.test(node.nodeValue)))){Element.remove(node);i--;}
if(node.nodeType==1){Element.cleanWhitespace(node);}}},empty:function(element){return $(element).innerHTML.match(/^\s*$/);},childOf:function(element,ancestor){element=$(element);ancestor=$(ancestor);while(element.parentNode){element=element.parentNode;if(element==ancestor){return true;}}
return false;},scrollTo:function(element){element=$(element);var x=element.x?element.x:element.offsetLeft,y=element.y?element.y:element.offsetTop;window.scrollTo(x,y);},getStyle:function(element,style){element=$(element);var value=element.style[style.camelize()];if(!value){if(document.defaultView&&document.defaultView.getComputedStyle){var css=document.defaultView.getComputedStyle(element,null);value=css?css.getPropertyValue(style):null;}else if(element.currentStyle){value=element.currentStyle[style.camelize()];}}
if(window.opera&&['left','top','right','bottom'].include(style)){if(Element.getStyle(element,'position')=='static'){value='auto';}}
return value=='auto'?null:value;},setStyle:function(element,style){element=$(element);for(var name in style){element.style[name.camelize()]=style[name];}},getDimensions:function(element){element=$(element);if(Element.getStyle(element,'display')!='none'){return{width:element.offsetWidth,height:element.offsetHeight};}
var els=element.style;var originalVisibility=els.visibility;var originalPosition=els.position;els.visibility='hidden';els.position='absolute';els.display='';var originalWidth=element.clientWidth;var originalHeight=element.clientHeight;els.display='none';els.position=originalPosition;els.visibility=originalVisibility;return{width:originalWidth,height:originalHeight};},makePositioned:function(element){element=$(element);var pos=Element.getStyle(element,'position');if(pos=='static'||!pos){element._madePositioned=true;element.style.position='relative';if(window.opera){element.style.top=0;element.style.left=0;}}},undoPositioned:function(element){element=$(element);if(element._madePositioned){element._madePositioned=undefined;element.style.position=element.style.top=element.style.left=element.style.bottom=element.style.right='';}},makeClipping:function(element){element=$(element);if(element._overflow){return;}
element._overflow=element.style.overflow;if((Element.getStyle(element,'overflow')||'visible')!='hidden'){element.style.overflow='hidden';}},undoClipping:function(element){element=$(element);if(element._overflow){return;}
element.style.overflow=element._overflow;element._overflow=undefined;}};Object.extend(Element,Element.Methods);var _nativeExtensions=false;if(!HTMLElement&&(/Konqueror|Safari|KHTML/.test(navigator.userAgent))){var HTMLElement={};HTMLElement.prototype=document.createElement('div').__proto__;}
Element.addMethods=function(methods){Object.extend(Element.Methods,methods||{});if(typeof HTMLElement!='undefined'){var methods=Element.Methods,cache=Element.extend.cache;for(property in methods){var value=methods[property];if(typeof value=='function'){HTMLElement.prototype[property]=cache.findOrStore(value);}}
_nativeExtensions=true;}};Element.addMethods();var Toggle=new Object();Toggle.display=Element.toggle;Abstract.Insertion=function(adjacency){this.adjacency=adjacency;};Abstract.Insertion.prototype={initialize:function(element,content){this.element=$(element);this.content=content.stripScripts();if(this.adjacency&&this.element.insertAdjacentHTML){try{this.element.insertAdjacentHTML(this.adjacency,this.content);}catch(e){var tagName=this.element.tagName.toLowerCase();if(tagName=='tbody'||tagName=='tr'){this.insertContent(this.contentFromAnonymousTable());}else{throw e;}}}else{this.range=this.element.ownerDocument.createRange();if(this.initializeRange){this.initializeRange();}
this.insertContent([this.range.createContextualFragment(this.content)]);}
setTimeout(function(){content.evalScripts();},10);},contentFromAnonymousTable:function(){var div=document.createElement('div');div.innerHTML='<table><tbody>'+this.content+'</tbody></table>';return $A(div.childNodes[0].childNodes[0].childNodes);}};var Insertion=new Object();Insertion.Before=Class.create();Insertion.Before.prototype=Object.extend(new Abstract.Insertion('beforeBegin'),{initializeRange:function(){this.range.setStartBefore(this.element);},insertContent:function(fragments){fragments.each((function(fragment){this.element.parentNode.insertBefore(fragment,this.element);}).bind(this));}});Insertion.Top=Class.create();Insertion.Top.prototype=Object.extend(new Abstract.Insertion('afterBegin'),{initializeRange:function(){this.range.selectNodeContents(this.element);this.range.collapse(true);},insertContent:function(fragments){fragments.reverse(false).each((function(fragment){this.element.insertBefore(fragment,this.element.firstChild);}).bind(this));}});Insertion.Bottom=Class.create();Insertion.Bottom.prototype=Object.extend(new Abstract.Insertion('beforeEnd'),{initializeRange:function(){this.range.selectNodeContents(this.element);this.range.collapse(this.element);},insertContent:function(fragments){fragments.each((function(fragment){this.element.appendChild(fragment);}).bind(this));}});Insertion.After=Class.create();Insertion.After.prototype=Object.extend(new Abstract.Insertion('afterEnd'),{initializeRange:function(){this.range.setStartAfter(this.element);},insertContent:function(fragments){fragments.each((function(fragment){this.element.parentNode.insertBefore(fragment,this.element.nextSibling);}).bind(this));}});Element.ClassNames=Class.create();Element.ClassNames.prototype={initialize:function(element){this.element=$(element);},_each:function(iterator){this.element.className.split(/\s+/).select(function(name){return name.length>0;})._each(iterator);},set:function(className){this.element.className=className;},add:function(classNameToAdd){if(this.include(classNameToAdd)){return;}
this.set(this.toArray().concat(classNameToAdd).join(' '));},remove:function(classNameToRemove){if(!this.include(classNameToRemove)){return;}
this.set(this.select(function(className){return className!=classNameToRemove;}).join(' '));},toString:function(){return this.toArray().join(' ');}};Object.extend(Element.ClassNames.prototype,Enumerable);var Selector=Class.create();Selector.prototype={initialize:function(expression){this.params={classNames:[]};this.expression=expression.toString().strip();this.parseExpression();this.compileMatcher();},parseExpression:function(){function abort(message){throw'Parse error in selector: '+message;}
if(this.expression==''){abort('empty expression');}
var params=this.params,expr=this.expression,match,modifier,clause,rest;while(expr.match(/^(.*)\[([a-z0-9_:-]+?)(?:([~\|!]?=)(?:"([^"]*)"|([^\]\s]*)))?\]$/i)){match=expr.match(/^(.*)\[([a-z0-9_:-]+?)(?:([~\|!]?=)(?:"([^"]*)"|([^\]\s]*)))?\]$/i);params.attributes=params.attributes||[];params.attributes.push({name:match[2],operator:match[3],value:match[4]||match[5]||''});expr=match[1];}
if(expr=='*'){this.params.wildcard=true;return this.params.wildcard;}
while(expr.match(/^([^a-z0-9_-])?([a-z0-9_-]+)(.*)/i)){match=expr.match(/^([^a-z0-9_-])?([a-z0-9_-]+)(.*)/i);modifier=match[1];clause=match[2];rest=match[3];switch(modifier){case'#':params.id=clause;break;case'.':params.classNames.push(clause);break;case'':case undefined:params.tagName=clause.toUpperCase();break;default:abort(expr.inspect());}
expr=rest;}
if(expr.length>0){abort(expr.inspect());}},buildMatchExpression:function(){var params=this.params,conditions=[],clause;if(params.wildcard){conditions.push('true');}
if(params.id){clause=params.id;conditions.push('element.id == '+clause.inspect());}
if(params.tagName){clause=params.tagName;conditions.push('element.tagName.toUpperCase() == '+clause.inspect());}
if(params.classNames.length>0){clause=params.classNames;for(var i=0;i<clause.length;i++){conditions.push('Element.hasClassName(element, '+clause[i].inspect()+')');}}
if(params.attributes){clause=params.attributes;clause.each(function(attribute){var value='element.getAttribute('+attribute.name.inspect()+')';var splitValueBy=function(delimiter){return value+' && '+value+'.split('+delimiter.inspect()+')';};switch(attribute.operator){case'=':conditions.push(value+' == '+attribute.value.inspect());break;case'~=':conditions.push(splitValueBy(' ')+'.include('+attribute.value.inspect()+')');break;case'|=':conditions.push(splitValueBy('-')+'.first().toUpperCase() == '+attribute.value.toUpperCase().inspect());break;case'!=':conditions.push(value+' != '+attribute.value.inspect());break;case'':case undefined:conditions.push(value+' != null');break;default:throw'Unknown operator '+attribute.operator+' in selector';}});}
return conditions.join(' && ');},compileMatcher:function(){this.match=new Function('element','if (!element.tagName) return false; return '+this.buildMatchExpression());},findElements:function(scope){var element;if($(this.params.id)){element=$(this.params.id);if(this.match(element)){if(!scope||Element.childOf(element,scope)){return[element];}}}
scope=(scope||document).getElementsByTagName(this.params.tagName||'*');var results=[];for(var i=0;i<scope.length;i++){if(this.match(element=scope[i])){results.push(Element.extend(element));}}
return results;},toString:function(){return this.expression;}};function $$(){return $A(arguments).map(function(expression){return expression.strip().split(/\s+/).inject([null],function(results,expr){var selector=new Selector(expr);return results.map(selector.findElements.bind(selector)).flatten();});}).flatten();}
var Field={clear:function(){for(var i=0;i<arguments.length;i++){$(arguments[i]).value='';}},focus:function(element){$(element).focus();},present:function(){for(var i=0;i<arguments.length;i++){if($(arguments[i]).value==''){return false;}}
return true;},select:function(element){$(element).select();},activate:function(element){element=$(element);element.focus();if(element.select){element.select();}},setCursorToEnd:function(element){try{range=element.createTextRange();range.collapse(true);range.moveStart('character',element.value.length);range.select();}
catch(e){element.focus();}}};var Form={serialize:function(form){var elements=Form.getElements($(form));var queryComponents=new Array();for(var i=0;i<elements.length;i++){var queryComponent=Form.Element.serialize(elements[i]);if(queryComponent){queryComponents.push(queryComponent);}}
return queryComponents.join('&');},getElements:function(form){form=$(form);var elements=new Array();for(var tagName in Form.Element.Serializers){var tagElements=form.getElementsByTagName(tagName);for(var j=0;j<tagElements.length;j++){elements.push(tagElements[j]);}}
return elements;},getInputs:function(form,typeName,name){form=$(form);var inputs=form.getElementsByTagName('input');if(!typeName&&!name){return inputs;}
var matchingInputs=new Array();for(var i=0;i<inputs.length;i++){var input=inputs[i];if((typeName&&input.type!=typeName)||(name&&input.name!=name)){continue;}
matchingInputs.push(input);}
return matchingInputs;},disable:function(form){var elements=Form.getElements(form);for(var i=0;i<elements.length;i++){var element=elements[i];element.blur();element.disabled='true';}},enable:function(form){var elements=Form.getElements(form);for(var i=0;i<elements.length;i++){var element=elements[i];element.disabled='';}},findFirstElement:function(form){return Form.getElements(form).find(function(element){return element.type!='hidden'&&!element.disabled&&['input','select','textarea'].include(element.tagName.toLowerCase());});},focusFirstElement:function(form){Field.activate(Form.findFirstElement(form));},reset:function(form){$(form).reset();}};Form.Element={serialize:function(element){element=$(element);var method=element.tagName.toLowerCase();var parameter=Form.Element.Serializers[method](element);if(parameter){var key=escape(parameter[0]);if(key.length==0){return;}
if(parameter[1].constructor!=Array){parameter[1]=[parameter[1]];}
return parameter[1].map(function(value){return key+'='+escape(value);}).join('&');}},getValue:function(element){element=$(element);var method=element.tagName.toLowerCase();var parameter=Form.Element.Serializers[method](element);if(parameter){return parameter[1];}}};Form.Element.Serializers={input:function(element){switch(element.type.toLowerCase()){case'submit':case'hidden':case'password':case'text':return Form.Element.Serializers.textarea(element);case'checkbox':case'radio':return Form.Element.Serializers.inputSelector(element);}
return false;},inputSelector:function(element){var groups=document.getElementsByName(element.name);var subValue=new Array();for(var i=0;i<groups.length;i++){if(groups[i].checked){subValue.push(groups[i].value);}}
if(subValue.length<1){subValue=[];}
return[element.name,subValue];},textarea:function(element){return[element.name,element.value];},select:function(element){return Form.Element.Serializers[element.type=='select-one'?'selectOne':'selectMany'](element);},selectOne:function(element){var value='',opt,index=element.selectedIndex;if(index>=0){opt=element.options[index];value=opt.value||opt.text;}
return[element.name,value];},selectMany:function(element){var value=[];for(var i=0;i<element.length;i++){var opt=element.options[i];if(opt.selected){value.push(opt.value||opt.text);}}
return[element.name,value];}};var $F=Form.Element.getValue;Abstract.TimedObserver=function(){};Abstract.TimedObserver.prototype={initialize:function(element,frequency,callback){this.frequency=frequency;this.element=$(element);this.callback=callback;this.lastValue=this.getValue();this.registerCallback();},registerCallback:function(){setInterval(this.onTimerEvent.bind(this),this.frequency*1000);},onTimerEvent:function(){var value=this.getValue();if(this.lastValue!=value){this.callback(this.element,value);this.lastValue=value;}}};Form.Element.Observer=Class.create();Form.Element.Observer.prototype=Object.extend(new Abstract.TimedObserver(),{getValue:function(){return Form.Element.getValue(this.element);}});Form.Observer=Class.create();Form.Observer.prototype=Object.extend(new Abstract.TimedObserver(),{getValue:function(){return Form.serialize(this.element);}});Abstract.EventObserver=function(){};Abstract.EventObserver.prototype={initialize:function(element,callback){this.element=$(element);this.callback=callback;this.lastValue=this.getValue();if(this.element.tagName.toLowerCase()=='form'){this.registerFormCallbacks();}
else{this.registerCallback(this.element);}},onElementEvent:function(){var value=this.getValue();if(this.lastValue!=value){this.callback(this.element,value);this.lastValue=value;}},registerFormCallbacks:function(){var elements=Form.getElements(this.element);for(var i=0;i<elements.length;i++){this.registerCallback(elements[i]);}},registerCallback:function(element){if(element.type){switch(element.type.toLowerCase()){case'checkbox':case'radio':Event.observe(element,'click',this.onElementEvent.bind(this));break;case'password':case'text':case'textarea':case'select-one':case'select-multiple':Event.observe(element,'change',this.onElementEvent.bind(this));break;}}}};Form.Element.EventObserver=Class.create();Form.Element.EventObserver.prototype=Object.extend(new Abstract.EventObserver(),{getValue:function(){return Form.Element.getValue(this.element);}});Form.EventObserver=Class.create();Form.EventObserver.prototype=Object.extend(new Abstract.EventObserver(),{getValue:function(){return Form.serialize(this.element);}});if(!window.Event){var Event=new Object();}
Object.extend(Event,{KEY_BACKSPACE:8,KEY_TAB:9,KEY_RETURN:13,KEY_ESC:27,KEY_LEFT:37,KEY_UP:38,KEY_RIGHT:39,KEY_DOWN:40,KEY_DELETE:46,element:function(event){return event.target||event.srcElement;},isLeftClick:function(event){return(((event.which)&&(event.which==1))||((event.button)&&(event.button==1)));},pointerX:function(event){return event.pageX||(event.clientX+
(document.documentElement.scrollLeft||document.body.scrollLeft));},pointerY:function(event){return event.pageY||(event.clientY+
(document.documentElement.scrollTop||document.body.scrollTop));},stop:function(event){if(event.preventDefault){event.preventDefault();event.stopPropagation();}else{event.returnValue=false;event.cancelBubble=true;}},findElement:function(event,tagName){var element=Event.element(event);while(element.parentNode&&(!element.tagName||(element.tagName.toUpperCase()!=tagName.toUpperCase()))){element=element.parentNode;}
return element;},observers:false,_observeAndCache:function(element,name,observer,useCapture){if(!this.observers){this.observers=[];}
if(element.addEventListener){this.observers.push([element,name,observer,useCapture]);element.addEventListener(name,observer,useCapture);}else if(element.attachEvent){this.observers.push([element,name,observer,useCapture]);element.attachEvent('on'+name,observer);}},unloadCache:function(){if(!Event.observers){return;}
for(var i=0;i<Event.observers.length;i++){Event.stopObserving.apply(this,Event.observers[i]);Event.observers[i][0]=null;}
Event.observers=false;},observe:function(element,name,observer,useCapture){var element=$(element);useCapture=useCapture||false;if(name=='keypress'&&(navigator.appVersion.match(/Konqueror|Safari|KHTML/)||element.attachEvent)){name='keydown';}
this._observeAndCache(element,name,observer,useCapture);},stopObserving:function(element,name,observer,useCapture){var element=$(element);useCapture=useCapture||false;if(name=='keypress'&&(navigator.appVersion.match(/Konqueror|Safari|KHTML/)||element.detachEvent)){name='keydown';}
if(element.removeEventListener){element.removeEventListener(name,observer,useCapture);}else if(element.detachEvent){element.detachEvent('on'+name,observer);}}});if(navigator.appVersion.match(/\bMSIE\b/)){Event.observe(window,'unload',Event.unloadCache,false);}
var Position={includeScrollOffsets:false,prepare:function(){this.deltaX=window.pageXOffset||document.documentElement.scrollLeft||document.body.scrollLeft||0;this.deltaY=window.pageYOffset||document.documentElement.scrollTop||document.body.scrollTop||0;},realOffset:function(element){var valueT=0,valueL=0;do{valueT+=element.scrollTop||0;valueL+=element.scrollLeft||0;element=element.parentNode;}while(element);return[valueL,valueT];},cumulativeOffset:function(element){var valueT=0,valueL=0;do{valueT+=element.offsetTop||0;valueL+=element.offsetLeft||0;element=element.offsetParent;}while(element);return[valueL,valueT];},positionedOffset:function(element){var valueT=0,valueL=0;do{valueT+=element.offsetTop||0;valueL+=element.offsetLeft||0;element=element.offsetParent;if(element){p=Element.getStyle(element,'position');if(p=='relative'||p=='absolute'){break;}}}while(element);return[valueL,valueT];},offsetParent:function(element){if(element.offsetParent){return element.offsetParent;}
if(element==document.body){return element;}
while((element=element.parentNode)&&element!=document.body){if(Element.getStyle(element,'position')!='static'){return element;}}
return document.body;},within:function(element,x,y){if(this.includeScrollOffsets){return this.withinIncludingScrolloffsets(element,x,y);}
this.xcomp=x;this.ycomp=y;this.offset=this.cumulativeOffset(element);return(y>=this.offset[1]&&y<this.offset[1]+element.offsetHeight&&x>=this.offset[0]&&x<this.offset[0]+element.offsetWidth);},withinIncludingScrolloffsets:function(element,x,y){var offsetcache=this.realOffset(element);this.xcomp=x+offsetcache[0]-this.deltaX;this.ycomp=y+offsetcache[1]-this.deltaY;this.offset=this.cumulativeOffset(element);return(this.ycomp>=this.offset[1]&&this.ycomp<this.offset[1]+element.offsetHeight&&this.xcomp>=this.offset[0]&&this.xcomp<this.offset[0]+element.offsetWidth);},overlap:function(mode,element){if(!mode){return 0;}
if(mode=='vertical'){return((this.offset[1]+element.offsetHeight)-this.ycomp)/element.offsetHeight;}
if(mode=='horizontal'){return((this.offset[0]+element.offsetWidth)-this.xcomp)/element.offsetWidth;}},clone:function(source,target){source=$(source);target=$(target);target.style.position='absolute';var offsets=this.cumulativeOffset(source);target.style.top=offsets[1]+'px';target.style.left=offsets[0]+'px';target.style.width=source.offsetWidth+'px';target.style.height=source.offsetHeight+'px';},page:function(forElement){var valueT=0,valueL=0;var element=forElement;do{valueT+=element.offsetTop||0;valueL+=element.offsetLeft||0;if(element.offsetParent==document.body){if(Element.getStyle(element,'position')=='absolute'){break;}}
element=element.offsetParent;}while(element);element=forElement;do{valueT-=element.scrollTop||0;valueL-=element.scrollLeft||0;element=element.parentNode;}while(element);return[valueL,valueT];},clone:function(source,target){var options=Object.extend({setLeft:true,setTop:true,setWidth:true,setHeight:true,offsetTop:0,offsetLeft:0},arguments[2]||{});source=$(source);var p=Position.page(source);target=$(target);var delta=[0,0];var parent=null;if(Element.getStyle(target,'position')=='absolute'){parent=Position.offsetParent(target);delta=Position.page(parent);}
if(parent==document.body){delta[0]-=document.body.offsetLeft;delta[1]-=document.body.offsetTop;}
if(options.setLeft){target.style.left=(p[0]-delta[0]+options.offsetLeft)+'px';}
if(options.setTop){target.style.top=(p[1]-delta[1]+options.offsetTop)+'px';}
if(options.setWidth){target.style.width=source.offsetWidth+'px';}
if(options.setHeight){target.style.height=source.offsetHeight+'px';}},absolutize:function(element){element=$(element);if(Element.getStyle(element,'position')=='absolute'){return;}
Position.prepare();var offsets=Position.cumulativeOffset(element);var top=offsets[1];var left=offsets[0];var width=element.clientWidth;var height=element.clientHeight;element._originalLeft=parseFloat(element.style.left||0);element._originalTop=parseFloat(element.style.top||0);element._originalWidth=element.style.width;element._originalHeight=element.style.height;element.style.position='absolute';element.style.top=top+'px';element.style.left=left+'px';element.style.width=width+'px';element.style.height=height+'px';var pos=Position.cumulativeOffset(element);var p=[0,1].map(function(i){return(offsets[i]-pos[i]);});var d=[p[0]+parseInt(Element.getStyle(element,'left')||0),p[1]+parseInt(Element.getStyle(element,'top')||0)];element.style.left=d[0]+'px';element.style.top=d[1]+'px';},relativize:function(element){element=$(element);if(Element.getStyle(element,'position')=='relative'){return;}
if(typeof(element._originalWidth)=='undefined'||typeof(element._originalHeight)=='undefined'){return;}
Position.prepare();var offsets=Position.cumulativeOffset(element);element.style.position='relative';var top=parseFloat(element.style.top||0);var left=parseFloat(element.style.left||0);element.style.top=top+'px';element.style.left=left+'px';element.style.height=element._originalHeight;element.style.width=element._originalWidth;var pos=Position.cumulativeOffset(element);var p=[0,1].map(function(i){return(offsets[i]-pos[i]);});var d=[p[0]+parseInt(Element.getStyle(element,'left')||0),p[1]+parseInt(Element.getStyle(element,'top')||0)];element.style.left=d[0]+'px';element.style.top=d[1]+'px';}};if(/Konqueror|Safari|KHTML/.test(navigator.userAgent)){Position.cumulativeOffset=function(element){var valueT=0,valueL=0;do{valueT+=element.offsetTop||0;valueL+=element.offsetLeft||0;if(element.offsetParent==document.body){if(Element.getStyle(element,'position')=='absolute'){break;}}
element=element.offsetParent;}while(element);return[valueL,valueT];};}
var App={cancelBubble:function(event){Event.stop(event);},Lang:{loading:'读取中...',refreshModuleBtnTitle:'刷新',createModule:'正在创建模块...',setBtn:'设置',closeSetBtn:'关闭设置',loadWidget:'请稍候，正在读取...',save:'保存',temp:''},Permit:{editModule:true},Actions:{imgPath:'http://img3.pp.sohu.com/ppp/blog/styles_ppp/images/'},Widgets:{},maxWidgetLoadTime:10000}
function registerWidget(w){App.Widgets[w]=eval(w);}
App.Module=Class.create();App.Module.prototype={initialize:function(options,isInit){this.options=Object.extend({id:null,type:null,isExpanded:true,share:true,floating:false,title:'',data:null,page:null,placeIn:document.body,placeBefore:null,newMode:false},options||{});Object.extend(this.options,{editMode:false,loaded:false,loadTime:0,maxLoadTime:App.maxWidgetLoadTime});this.build();this.m_content=this.getModuleContent();if(App.Permit.editModule){this.m_edit=this.getEditContent();this.hideEditMode();this.hideEditBtn();}
if(!this.options.newMode){this.hideRefreshBtn();}
this.setIco(this.options.ico);this.options.isExpanded?'':this.swapShowHide(false,isInit);this.attachContent();},save:function(data,title){if(!data&&title===null){return;}
if(typeof data!='undefined'&&data){this.options.data=data;}
if(typeof title!='undefined'&&title!==null){this.options.title=title;}
this.endSave();},endSave:function(){if(this.content&&this.content.endSave){this.content.endSave();}
this.closeEdit();},attachContent:function(){this.initWidget();},initWidget:function(){var widget={ableDel:false};this.w_path="";this.content=new App.Widgets[this.options.type](this.options.data,this.m_content,this.m_edit,this.w_path);this.content.id=this.options.id;this.content.setIco=this.setIco.bind(this);this.content.setTitle=this.setTitle.bind(this);this.content.getTitle=this.getTitle.bind(this);this.content.resetControls=this.resetControls.bind(this);this.resetControls();if(App.Permit.editModule&&!this.options.newMode){if(widget.ableDel){this.showCloseBtn();}
else{this.hideCloseBtn();}}
this.content.initialize();},resetControls:function(){if(App.Permit.editModule){if(typeof this.content.edit=='function'){this.showEditBtn();this.content.save=this.save.bind(this);this.content.closeEdit=this.closeEdit.bind(this);}else{this.hideEditBtn();}}
if(typeof this.content.refresh=='function'){if(!this.options.newMode){this.showRefreshBtn();}
this.content.loaded=this.loaded.bind(this);}else{this.hideRefreshBtn();}},showWidgetLoading:function(){var str='';str+=App.Lang.loadWidget;this.m_content.innerHTML=str;},build:function(){var divModule=document.createElement('div');this.element=divModule;divModule.className='mod';divModule.id=this.options.id;var arr=[];arr.push('<div class="modFrame">');arr.push('<table cellspacing="0" cellpadding="0" class="modTable">');arr.push('<thead><tr>');arr.push('<td class="mheader lt"></td>');arr.push('<td class="mheader t"><div class="modHeader clearfix"></div></td>');arr.push('<td class="mheader rt"></td>');arr.push('</tr></thead>');arr.push('<tbody>');arr.push('<tr>');arr.push('<td class="mneck l"></td>');arr.push('<td class="mneck ec"><div class="modEditCon"></div></td>');arr.push('<td class="mneck r"></td>');arr.push('</tr>');arr.push('<tr>');arr.push('<td class="mbody l"></td>');arr.push('<td class="mbody c"><div class="modCon">'+App.Lang.loading+'</div></td>');arr.push('<td class="mbody r"></td>');arr.push('</tr></tbody>');arr.push('<tfoot><tr>');arr.push('<td class="mfooter lb"></td>');arr.push('<td class="mfooter b"></td>');arr.push('<td class="mfooter rb"></td>');arr.push('</tr></tfoot>');arr.push('</table>');arr.push('</div>');divModule.innerHTML=arr.join('');arr=null;this.eventCancelBubble=App.cancelBubble.bindAsEventListener(this);var divModuleHeader=this.getModTable().firstChild.firstChild.childNodes[1].firstChild;if(!this.options.newMode){var divShowHide=document.createElement('div');this.elm_showHide=divShowHide;divShowHide.className='modShow';divShowHide.title=App.Lang.showHideModuleBtnTitle;Event.observe(divShowHide,'mousedown',this.eventCancelBubble);this.eventSwapShowHide=this.swapShowHide.bindAsEventListener(this);Event.observe(divShowHide,'click',this.eventSwapShowHide);divModuleHeader.appendChild(divShowHide);}
if(App.Permit.editModule){if(!this.options.newMode){var divClose=document.createElement('div');this.elm_close=divClose;divClose.className='modCls';Event.observe(divClose,'mousedown',this.eventCancelBubble);Event.observe(divClose,'click',this.eventCancelBubble);divModuleHeader.appendChild(divClose);}
var divEdit=document.createElement('div');this.elm_edit=divEdit;divEdit.className='modEdit';divEdit.innerHTML='<a href="javascript:void(0)">'+App.Lang.setBtn+'</a>';Event.observe(divEdit,'mousedown',this.eventCancelBubble);this.eventSwapEdit=this.swapEditMode.bindAsEventListener(this);Event.observe(divEdit,'click',this.eventSwapEdit);divModuleHeader.appendChild(divEdit);}
if(!this.options.newMode){var divRefresh=document.createElement('div');this.elm_refresh=divRefresh;divRefresh.className='modRfs';divRefresh.title=App.Lang.refreshModuleBtnTitle;Event.observe(divRefresh,'mousedown',this.eventCancelBubble);this.eventRefresh=this.refresh.bindAsEventListener(this);Event.observe(divRefresh,'click',this.eventRefresh);divModuleHeader.appendChild(divRefresh);}
var divIco=document.createElement('div');this.elm_ico=divIco;divIco.className='modIco';divIco.innerHTML='<img src="'+App.Actions.imgPath+'spacer.gif" />';divModuleHeader.appendChild(divIco);var divTitle=document.createElement('div');this.elm_title=divTitle;divTitle.className='modTitle';divTitle.innerHTML=this.options.title||App.Lang.createModule;divModuleHeader.appendChild(divTitle);this.options.placeIn.appendChild(divModule);},getModTable:function(){return(this.element.firstChild.firstChild);},getContentPanel:function(){var mod_table=this.getModTable();var contentPanel=mod_table.childNodes[1].childNodes[1];return contentPanel;},getModuleContent:function(){var contentPanel=this.getContentPanel();var moduleContent=contentPanel.childNodes[1].firstChild;return moduleContent;},refresh:function(event){if(this.content&&this.content.refresh&&this.options.loaded){this.options.loaded=false;this.content.refresh();}},swapEditMode:function(){this.options.editMode?this.closeEdit():this.edit();},getEditPanel:function(){var mod_table=this.getModTable();var editPanel=mod_table.childNodes[1].firstChild;return editPanel;},getEditContent:function(){var editPanel=this.getEditPanel();var editContent=editPanel.childNodes[1].firstChild;return editContent;},hideEditMode:function(){var editPanel=this.getEditPanel();Element.hide(editPanel);this.setEditBtn();},setEditBtn:function(){this.elm_edit.firstChild.innerHTML="设置";},hideEditBtn:function(){Element.hide(this.elm_edit);},showRefreshBtn:function(){Element.show(this.elm_refresh);},hideRefreshBtn:function(){Element.hide(this.elm_refresh);},loaded:function(){this.options.loaded=true;},showCloseBtn:function(){Element.show(this.elm_close);},hideCloseBtn:function(){Element.hide(this.elm_close);},setIco:function(src){if(!src){Element.hide(this.elm_ico);return;}
var _img=this.elm_ico.firstChild;_img.src=src;_img.onload=function(){if(this.height>16){this.height='16';}};Element.show(this.elm_ico);},swapShowHide:function(opr,isInit){this.lastIsExpanded=this.options.isExpanded;if(typeof arguments[0]=='boolean'){arguments[0]?this.show():this.hide();}else{this.options.isExpanded?this.hide():this.show();}},setTitle:function(title,cover){if(!title){return;}
this.elm_title.innerHTML=title;},getTitle:function(){return(this.elm_title.innerHTML);},showEditBtn:function(){Element.show(this.elm_edit);},edit:function(event){this.options.editMode=true;if(this.content&&this.content.edit){this.content.edit();}
this.showEditMode();this.show();},closeEdit:function(event){this.options.editMode=false;if(this.content&&this.content.onCloseEdit){this.content.onCloseEdit();}
this.hideEditMode();},showEditMode:function(){var editPanel=this.getEditPanel();Element.show(editPanel);this.setCloseEditBtn();},setCloseEditBtn:function(){this.elm_edit.firstChild.innerHTML=App.Lang.closeSetBtn;},show:function(notSetOpt){Element.show(this.getContentPanel());if(Element.hasClassName(this.elm_showHide,'modHide')){Element.removeClassName(this.elm_showHide,'modHide');}
Element.addClassName(this.elm_showHide,'modShow');if(!notSetOpt){this.options.isExpanded=true;}},hide:function(notSetOpt){Element.hide(this.getContentPanel());if(Element.hasClassName(this.elm_showHide,'modShow')){Element.removeClassName(this.elm_showHide,'modShow');}
Element.addClassName(this.elm_showHide,'modHide');if(!notSetOpt){this.options.isExpanded=false;}}};
var UWA={};
UWA.innerXML=function(node){var str='';var nodes=node.childNodes;if(nodes){for(var i=0;i<nodes.length;i++){var nodeNow=nodes[i];if(nodeNow.nodeType==3){str+=nodeNow.data;}else{if(nodeNow.xml){str+=nodeNow.xml;}else{var serializer=new XMLSerializer();str+=serializer.serializeToString(nodeNow);}}}}
return str;}
UWA.log=function(obj){if(window.console){console.log(obj);}else{if((App.Permit.able3rdDev||App.Permit.ableDemo)&&document.readyState&&document.readyState=="complete"){if(obj instanceof Error){$LR("--------- Error ---------");$LR("name: "+obj.name);$LR("number:"+(obj.number&0xFFFF));$LR("message: "+obj.message);$LR("-------------------------");}else{$LR(obj.toString());}}}}
UWA.Config={moduler:"/px",ajax:"/py"}
var widget={};function documentOnReady(){UWA.Config.defaultWidget="this";UWA.Config.container=document.body;UWA.Config.ajax="";UWA.Config.moduler="";loadWidgetBaseInfo();var uwa_widget={title:'uwa widget',desc:'uwa widget',author:'Jady',site:'http://testgood.blog.sohu.com',data:{path:UWA.Config.defaultWidget},placeIn:$(UWA.Config.container),type:'uwa_widget',path:'uwa_widget/',sys:false,gal:'base'}
new App.Module(uwa_widget);}
window.onload=documentOnReady;
UWA.Data={getXml:function(url,callback){this.request(url,{type:"xml",parameters:"ct=text%2Fxml",onComplete:callback});},getText:function(url,callback){this.request(url,{type:"text",onComplete:callback});},getJson:function(url,callback){this.request(url,{type:"json",onComplete:callback});},getModule:function(url,callback,errorCallback,isUseCache){var request={type:"xml",proxy:"moduler",onComplete:callback,onFailure:errorCallback}
if(!isUseCache)request.parameters="ca=0";this.request(url,request);},getFeed:function(url,callback){},request:function(url,request){request=Object.extend({method:"get",proxy:"ajax",type:"text",parameters:""},request||{});if(typeof(request.onComplete)!="function")request.onComplete=function(){}
var urlStr=UWA.Config[request.proxy];if(urlStr&&urlStr!=""){url=urlStr+"?url="+encodeURIComponent(url)+"&c="+new Date().getTime();}else{url+=(url.match(/\?/)?'&':'?')+"_ow_c="+new Date().getTime();}
if(!request.onFailure)request.onFailure=this.onFailure;request.onSuccess=request.onComplete;request.onComplete=null;switch(request.type){case"text":var callback=request.onSuccess;request.onSuccess=function(transport){try{callback(transport.responseText);}catch(e){UWA.log(e);}}
new Ajax.Request(url,request);break;case"json":var callback=request.onSuccess;request.onSuccess=function(transport){try{var data=eval("("+transport.responseText+")");callback(data);}catch(e){UWA.log(e);}}
new Ajax.Request(url,request);break;case'xml':var callback=request.onSuccess;request.requestHeaders=['Content-type','text/xml'];request.onSuccess=function(transport){try{callback(transport.responseXML,transport);}catch(e){UWA.log(e);}}
new Ajax.Request(url,request);break;}},onFailure:function(transport){UWA.log("status:"+transport.status+";statusText:"+transport.statusText);}}
UWA.Element={addClassName:function(className){if(!this.hasClassName(className))this.className=(this.className.length==0?"":(this.className+" "))+className;},addContent:function(content){switch(typeof(content)){case"string":case"number":var div=document.createElement("div");div.innerHTML=content;this.appendChild(div);break;case"object":this.appendChild(content);break;}},appendText:function(text){var textN=document.createTextNode(text);this.appendChild(textN);},empty:function(){this.innerHTML="";},getDimensions:function(){if(this.style.display!=null&&this.style.display!="none"){return{width:this.offsetWidth,height:this.offsetHeight}}
var els=this.style;var originalVisibility=els.visibility;var originalPosition=els.position;var originalDisplay=els.display;els.position='absolute';els.visibility='hidden';els.display='block';var originalWidth=this.clientWidth;var originalHeight=this.clientHeight;els.display=originalDisplay;els.position=originalPosition;els.visibility=originalVisibility;return{width:originalWidth,height:originalHeight}},getElementsByClassName:function(className){var childs=this.all?this.all:this.getElementsByTagName("*");var eles=[];for(var i=0;i<childs.length;i++){if(childs[i].className.match(new RegExp("(^|\\s)"+className+"(\\s|$)"))){eles.push(childs[i]);}}
return eles;},getParent:function(){return this.parentNode;},getChildren:function(){return this.childNodes;},hasClassName:function(className){return this.className.match(new RegExp("(^|\\s)"+className+"(\\s|$)"));},hide:function(){this.style.display="none";},remove:function(){this.parentNode.removeChild(this);},removeClassName:function(className){this.className=this.className.replace(new RegExp('(^|\\s)'+className+'(\\s|$)'),'$1').trim();},setText:function(text){this.innerHTML="";this.appendText(text);},setHTML:function(html){this.innerHTML=html;},setContent:function(content){this.innerHTML="";this.addContent(content);},setStyle:function(property,value){this.style[property]=value;},show:function(){this.style.display="";},toggle:function(){this.style.display=this.style.display=="none"?"":"none";}}
UWA.$element=function(element){var obj=typeof(element)=="string"?document.getElementById(element):element;if(!obj.isUwaExtended){Object.extend(obj,UWA.Element);obj.isUwaExtended=true;}
return obj;}
UWA.Reference={config:{base:[["name","","string"],["label","","string"],["defaultValue",undefined,"string"]],text:[],boolean:[["onchange",false,"boolean"],["defaultValue","false","string"]],hidden:[],range:[["onchange",false,"boolean"],["min","1","string"],["max","1","string"],["step","1","string"],["defaultValue",undefined,"string"]],list:[["onchange",false,"boolean"]],password:[]},getData:function(element){var object={};this.parseData(this.config.base,element,object);var type=element.getAttribute("type")==undefined?"text":element.getAttribute("type").toLowerCase();object.type=type;this[type+"Data"](element,object);return object;},textData:function(element,object){},booleanData:function(element,object){this.parseData(this.config.boolean,element,object);},hiddenData:function(element,object){},rangeData:function(element,object){this.parseData(this.config.range,element,object);},listData:function(element,object){this.parseData(this.config.list,element,object);var options=element.getElementsByTagName("option");object.options=[];for(var i=0;i<options.length;i++){object.options.push({label:options[i].getAttribute("label"),value:options[i].getAttribute("value")});}},passwordData:function(element,object){},parseData:function(config,element,object){for(var i=0;i<config.length;i++){var value=element.getAttribute(config[i][0]);if(value==null){object[config[i][0]]=config[i][1];}else{switch(config[i][2]){case"number":value=parseFloat(value);break;case"boolean":value=value.toLowerCase()=="true";break;}
object[config[i][0]]=value;}}
return object;},bindObjData:function(config,obj){for(var i=0;i<config.length;i++){if(typeof(obj[config[i][0]])!=config[i][2]){obj[config[i][0]]=config[i][1];}}},bindData:function(obj){this.bindObjData(this.config.base,obj);this.bindObjData(this.config[obj.type],obj);return obj;}}
UWA.Widget=function(){}
UWA.Widget.prototype.initialize=function(title,body,scripts){if(UWA.Config.fileInPage){Object.extend(this,widget);widget=this;}else{this.setScripts(scripts);}
this.setTitle(title);this.setBody(body);}
UWA.Widget.prototype.setScripts=function(scripts){var widget=this;if(scripts&&scripts.length&&scripts.length>0){for(var i=0;i<scripts.length;i++){eval(scripts[i]);}}}
UWA.Widget.prototype.onResize=function(){}
UWA.Widget.prototype.onSearch=function(){}
UWA.Widget.prototype.onResetSearch=function(){}
UWA.Widget.prototype.onKeyboardAction=function(){}
UWA.Widget.prototype.addBody=function(content){this.body.addContent(content);}
UWA.Widget.prototype.createElement=function(tagName){if(tagName=="script")return false;var el=document.createElement(tagName);return UWA.$element(el);}
UWA.Widget.prototype.getValue=function(name){}
UWA.Widget.prototype.openURL=function(url){window.open(url);}
UWA.Widget.prototype.setBody=function(content){this.body.innerHTML=content;}
UWA.Widget.prototype.setTitle=function(title){}
UWA.Widget.prototype.setValue=function(name,value){}
UWA.Widget.prototype.log=function(obj){}
UWA.Widget.prototype.setAutoRefresh=function(delay){}
UWA.Widget.prototype.setUnreadCount=function(count){}
UWA.Widget.prototype.setSearchResultCount=function(count){}
UWA.WidgetLib={libs:[],getWidgetClassId:function(path){var pathLower=path.toLowerCase();var libs=this.libs;for(var i=0;i<libs.length;i++){if(libs[i].path==pathLower){return i;}}
return-1;},getWidget:function(path,callback,isUseCache){if(isUseCache){var widgetLib=null;var index=this.getWidgetClassId(path);if(index>=0){widgetLib=this.libs[index];switch(widgetLib.status){case-1:widgetWrapper=widgetLib.wrapper;break;case 0:widgetLib.callbacks.push(callback);break;case 1:widgetWrapper=this.libs[index].wrapper;break;}}else{widgetLib={path:path.toLowerCase(),status:0,wrapper:null,callbacks:[callback]};this.libs.push(widgetLib);}
if(widgetLib.status==0){this.requestWidget(path);}else{callback(widgetLib.wrapper);}}else{this.requestWidgetNC(path,callback);}},requestWidget:function(url){UWA.Data.getModule(url,this.loadedWidgetXml.bind(this,url),this.loadFailure.bind(this,url),true);},requestWidgetNC:function(url,callback){UWA.Data.getModule(url,this.loadedWidgetXmlNC.bind(this,url,callback),this.loadFailureNC.bind(this,url,callback),false);},loadFailure:function(path,ajax){var index=this.getWidgetClassId(path);if(index>=0){var widget=this.libs[index];widget.status=-1;widget.wrapper=null;var callbacks=widget.callbacks;while(callbacks.length>0){var callback=callbacks.pop();callback(widget.wrapper);}}},loadedWidgetXml:function(path,xmlDoc,ajax){try{var wrapper=UWA.WidgetWrapper.getFromXml(xmlDoc,ajax);}catch(e){UWA.log(e);return;}
var index=this.getWidgetClassId(path);if(index>=0){wrapper.classId=index;var widget=this.libs[index];widget.status=1;widget.wrapper=wrapper;var callbacks=widget.callbacks;while(callbacks.length>0){var callback=callbacks.pop();callback(wrapper);}}},loadFailureNC:function(path,callback,ajax){callback(null);},loadedWidgetXmlNC:function(path,callback,xmlDoc,ajax){try{var wrapper=UWA.WidgetWrapper.getFromXml(xmlDoc,ajax);}catch(e){UWA.log(e);return;}
callback(wrapper);}}
UWA.WidgetWrapper=function(isPrivate){this._from="";this._xml=null;this._obj=null;this.classId=0;this.isPrivate=(typeof(isPrivate)=="boolean")?isPrivate:true;this._intro=null;this._scripts=null;this._refs=null;this._refDom=null;this._body=null;}
UWA.WidgetWrapper.prototype.getDefaultBaseInfo=function(){return{title:"",icon:"",author:"",website:"",description:"",version:"",keywords:"",screenshot:"",thumbnail:"",apiVersion:"",debugMode:false,autoRefresh:0}}
UWA.WidgetWrapper.prototype.parseBaseInfo=function(){if(this._intro==null){this._intro=this.getDefaultBaseInfo();this._scripts="";this._body="";if(this._from=="xml"||this._from=="this"){try{var isXml=this._from=="xml";if(isXml){var doc=this._xml.documentElement;var head=doc.getElementsByTagName("head")[0];var body=doc.getElementsByTagName("body")[0];}else{var doc=document;var head=doc.getElementsByTagName("head")[0];var body=doc.body;}
if(isXml){var title=head.getElementsByTagName("title")[0];this._intro.title=title.text||title.firstChild.data;}else{this._intro.title=doc.title;}
var links=head.getElementsByTagName("link");for(var i=0;i<links.length;i++){if(links[i].getAttribute("rel")=="icon"){this._intro.icon=links[i].getAttribute("href");break;}}
var metas=head.getElementsByTagName("meta");for(var i=0;i<metas.length;i++){var typeName=metas[i].getAttribute("name");var typeValue=metas[i].getAttribute("content");switch(typeName){case"debugMode":typeValue=typeValue=="true";break;case"autoRefresh":try{typeValue=parseInt(typeValue);}catch(e){typeValue=0;}
break;}
this._intro[typeName]=typeValue;}
var styles=head.getElementsByTagName("style");var styleStr="";for(var i=0;i<styles.length;i++){if(styles[i].getAttribute("src")==null){styleStr+=UWA.innerXML(styles[i]);}}
styleStr=styleStr.trim();if(styleStr.length>0){styleStr=styleStr.replace(/#moduleContent/g,'');styleStr=styleStr.replace(/\n\s*([a-zA-z0-9\.\-, :#]*)\s*([{|,])/g,"\n\.uwa_widget_"+this.classId+" $1$2");var styleEle=document.createElement("style");styleEle.setAttribute("type","text/css");if(styleEle.styleSheet){styleEle.styleSheet.cssText=styleStr;}else{styleEle.appendChild(document.createTextNode(styleStr));}
document.getElementsByTagName("head")[0].appendChild(styleEle);}
this._scripts=[];if(isXml){var scripts=head.getElementsByTagName("script");for(var i=0;i<scripts.length;i++){for(var j=0;j<scripts[i].childNodes.length;j++){var nodeType=scripts[i].childNodes[j].nodeType;if(nodeType==8||nodeType==4){this._scripts.push(scripts[i].childNodes[j].nodeValue);}}}}
this._refDom=head.getElementsByTagName("preference");if(isXml){this._body=UWA.innerXML(body);}else{this._body=body.innerHTML;}}catch(e){throw new SyntaxError("此文档不是一个有效的SOW Widget文档");}}else if(this._from=="obj"){this._intro=this._obj.intro;this._scripts=this._obj.scripts;this._refDom=this._obj.refs;this._body=this._obj.body;}}
this.parseRef();}
UWA.WidgetWrapper.prototype.parseRef=function(){if(this._refs==null){this._refs=[];var dataFuncName=this._from=="xml"||this._from=="this"?"getData":"bindData";var displayCount=0;for(var i=0;i<this._refDom.length;i++){var item=UWA.Reference[dataFuncName](this._refDom[i]);this._refs.push(item);this._refs[item.name]=item;}}}
UWA.WidgetWrapper.prototype.getIntro=function(){this.parseBaseInfo();return this._intro;}
UWA.WidgetWrapper.prototype.getScripts=function(){this.parseBaseInfo();return this._scripts;}
UWA.WidgetWrapper.prototype.getPreferences=function(){this.parseBaseInfo();return this._refs;}
UWA.WidgetWrapper.prototype.getBody=function(){this.parseBaseInfo();return this._body;}
UWA.WidgetWrapper.getFromThis=function(){var wrapper=new UWA.WidgetWrapper(false);wrapper._from="this";return wrapper;}
UWA.WidgetWrapper.getFromXml=function(xmlDom,ajax){if(xmlDom&&xmlDom.documentElement){var isPrivate=false;if(ajax&&ajax.getResponseHeader("Widget-Status")=="1"){isPrivate=true;}
var wrapper=new UWA.WidgetWrapper(isPrivate);wrapper._from="xml";wrapper._xml=xmlDom;return wrapper;}else{var error='';if(xmlDom.parseError&&xmlDom.parseError.reason){error+="-&lt;filepos:"+xmlDom.parseError.filepos+"; line:"+xmlDom.parseError.line+"; linepos:"+xmlDom.parseError.line+"; reason:"+xmlDom.parseError.reason;}
throw new SyntaxError("此文档不是一个标准的XML文档，不符合SOW Widget文档规范"+error);}}
UWA.WidgetWrapper.getFromObj=function(obj){var wrapper=new UWA.WidgetWrapper();wrapper._from="obj";wrapper._obj=obj;return wrapper;}
function loadWidgetBaseInfo(){var xmlDoc=UWA.WidgetWrapper.getFromThis();xmlDoc.parseBaseInfo();UWA.WidgetLib.libs[0]={path:UWA.Config.defaultWidget,status:1,wrapper:xmlDoc,callback:[]}
document.body.innerHTML="";}
UWA.Controls={};
UWA.Controls.Pager=function(params){this.module=params.module;this.limit=parseInt(params.limit);this.offset=parseInt(params.offset);this.dataArray=params.dataArray;}
UWA.Controls.Pager.prototype.getContent=function(){var ctr=document.createElement("div");ctr.className="pager";if(this.offset>0){var pre=document.createElement("a");pre.className="prev";pre.href="javascript:void(0);";pre.innerHTML="上一页";pre.onclick=this.onChange.bind(this,this.offset-this.limit);ctr.appendChild(pre);}
if(this.offset<this.dataArray.length-this.limit){var next=document.createElement("a");next.className="next";next.href="javascript:void(0);";next.innerHTML="下一页";next.onclick=this.onChange.bind(this,this.offset+this.limit);ctr.appendChild(next);}
return ctr;}
UWA.Controls.Pager.prototype.getDom=function(){return this.getContent();}
UWA.Controls.Pager.prototype.onChange=function(offset){}
UWA.Controls.TabView=function(options){this.initialize(options);}
UWA.Controls.TabView.prototype={setOptions:function(options){this.options={autohideDropdowns:true,tabSetClass:"tabSet",tabListClass:"tabList",tabContentClass:"tabContent",softPadding:false,orientation:'top',dataKey:'text',extendedAction:false}
Object.extend(this.options,options||{});},initialize:function(options){this.setOptions(options);this.dataItems={};this.selectedTab=null;this.selectedIndex=this.options.selectedIndex||0;},_createTabSet:function(){this.tabSet=document.createElement("div");this.tabSet.className=this.options.tabSetClass;this.tabList=document.createElement("ul");this.tabList.className=this.options.tabListClass+" autoclear";this.tabList.style.padding='0';if(/^(top)|(bottom)|(left)|(right)$/.test(this.options.orientation)){Element.addClassName(this.tabList,this.options.orientation);}
this.tabSet.appendChild(this.tabList);},appendTo:function(element){if(!this.tabSet)this._createTabSet();if(!this.selectedTab&&this.tabList.hasChildNodes())this.selectTab(0,false);$(element).appendChild(this.tabSet);},addTab:function(name,dataItem,options){if(!this.tabSet)this._createTabSet();if(typeof options=='undefined')options={}
var li=document.createElement("li");li.className="tab";li.setAttribute("name",name);li.onclick=this.eventTabClicked.bindAsEventListener(this);if(options.staticText){li.setAttribute('static','static');}
var a=document.createElement("a");a.href="#";a.target="_blank";a.style.whiteSpace="nowrap";a.onclick=function(){return false;}
if(dataItem.length){if(dataItem[0].image){var imgElement=document.createElement("img");imgElement.src=dataItem[0].image;a.appendChild(imgElement);}
else{if(dataItem[0].picto){var picto=document.createElement("img");picto.src=dataItem[0].picto;picto.style.marginRight="4px";picto.style.marginBottom="-2px";a.appendChild(picto);}
else if(dataItem[0].icon){var icon=document.createElement("img");icon.src=dataItem[0].icon;icon.style.marginRight="4px";icon.style.marginBottom="-2px";a.appendChild(icon);}
var textElement=document.createElement("span");textElement.appendChild(document.createTextNode(options.staticText||dataItem[0].text));a.appendChild(textElement);}
li.setAttribute("key",dataItem[0][this.options.dataKey]);var dropdownElement=document.createElement("span");dropdownElement.className="dropdown";do{var uniqueId="dropdownTab-"+(Math.ceil(Math.random()*1000));}
while($(uniqueId))
dropdownElement.setAttribute("id",uniqueId);var placeHolder=document.createElement("img");placeHolder.src="http://ow.blog.sohu.com/styles/images/s.gif";placeHolder.width=14;placeHolder.height=14;placeHolder.style.verticalAlign="middle";placeHolder.className="placeHolder";dropdownElement.appendChild(placeHolder);a.appendChild(dropdownElement);dropdownElement.onmousedown=this.eventDropDown.bindAsEventListener(this);}
else{if(dataItem.image){var imgElement=document.createElement("img");imgElement.src=dataItem.image;a.appendChild(imgElement);}
else{if(dataItem.picto){var picto=document.createElement("img");picto.src=dataItem.picto;picto.style.marginRight="4px";picto.style.marginBottom="-2px";a.appendChild(picto);}
else if(dataItem.icon){var icon=document.createElement("img");icon.src=dataItem.icon;icon.style.marginRight="4px";icon.style.marginBottom="-2px";a.appendChild(icon);}
a.appendChild(document.createTextNode(dataItem.text));}
li.setAttribute("key",dataItem[this.options.dataKey]);}
li.appendChild(a);if(this.selectedTab==null){}
this.tabList.appendChild(li);this.createTabContent(name);this.dataItems[name]=dataItem;return li;},removeTab:function(name){var tabItem=this.getTab(name);Element.remove(tabItem);},addExternalLink:function(name,href){var tabItem=this.getTab(name);tabItem.firstChild.setAttribute("href",href);},eventTabClicked:function(e){if(Event.element(e).className=="placeHolder"){return false;}
var sender=Event.findElement(e,"LI");if(!Element.hasClassName(sender,'disabled')){this.selectTab(sender);}
return false;},eventExtendedActionClicked:function(e){this.hidePopupMenu();this._notify('extendedActionClicked');return false;},enableTab:function(name,enable){var tabItem=this.getTab(name);if(enable)Element.removeClassName(tabItem,'disabled');else Element.addClassName(tabItem,'disabled');},selectTab:function(tabItem,notify){if(typeof tabItem=='number'||typeof tabItem=='string'){tabItem=this.getTab(tabItem);}
var name=tabItem.getAttribute('name');if(this.selectedTab&&(this.selectedTab.getAttribute('name')==name)){return;}
var items=this.tabList.getElementsByTagName('li');for(var i=0,li;li=items[i];i++){Element.removeClassName(li,'selected');if(this.popupMenu)this.hidePopupMenu();if(this.options.autohideDropdowns){var dropdowns=$(li).getElementsByClassName('dropdown');$A(dropdowns).each(function(el){Element.hide(el)});}}
Element.addClassName(tabItem,'selected');if(this.options.autohideDropdowns){var dropdowns=$(tabItem).getElementsByClassName('dropdown');$A(dropdowns).each(function(el){Element.show(el)});}
for(var i=0,content;content=this.contentArray[i];i++){if(name==content.getAttribute('name'))Element.show(content);else Element.hide(content);}
this.selectedTab=tabItem;this.selectedIndex=tabItem.getAttribute('index');if(notify===false)return;this._notify('activeTabChange');},hide:function(){Element.hide(this.tabSet);},show:function(){Element.show(this.tabSet);},hideTabList:function(){Element.hide(this.tabList);},showTabList:function(){Element.show(this.tabList);},reload:function(){this._notify('activeTabChange');},eventDropDown:function(e){var sender=Event.findElement(e,"LI");this.popupMenu=$('minitabsOptions');if(!this.popupMenu){this.popupMenu=document.createElement('ul');this.popupMenu.setAttribute('id','minitabsOptions');this.popupMenu.className='popupMenu';this.popupMenu.style.position='absolute';document.getElementsByTagName('body').item(0).appendChild(this.popupMenu);Element.hide(this.popupMenu);Event.observe(document,'mousedown',this.hidePopupMenu.bindAsEventListener(this));}
var dropdownButton=$(sender).getElementsByClassName('dropdown')[0];if(Element.visible(this.popupMenu)&&this.popupMenu.getAttribute("dropdownId")==dropdownButton.id){this.hidePopupMenu();return;}
this._showPopupMenu(sender);this.popupMenu.setAttribute("dropdownId",dropdownButton.id);Event.stop(e);return false;},getTabContent:function(name){if(typeof name=='number'){return this.contentArray.detect(function(el){return el.getAttribute("index")==name;});}
return this.contentArray.detect(function(el){return el.getAttribute("name")==name;});},setContent:function(name,content){var node=this.getTabContent(name);if(node){if(typeof content=='string'){node.innerHTML=content;}
else{node.innerHTML='';node.appendChild(content);}}},getTab:function(name){if(typeof name=='string'||typeof name=='number'){var items=this.tabList.getElementsByTagName('li');for(var i=0,item;item=items[i];i++){if(typeof name=='number'&&name==i)return item;if(name==item.getAttribute('name'))return item;}}
return name;},observe:function(name,observer){if(!this.observers)this.observers=[];this.observers.push([name,observer]);},_notify:function(event){if(!this.observers)return;var sender=this.selectedTab;var eventArgs=this.dataItems[sender.getAttribute('name')];if(eventArgs.length){var dataKey=this.options.dataKey;eventArgs=eventArgs.detect(function(el){return el[dataKey]==sender.getAttribute('key')});}
this.observers.each(function(observer){if(observer[0]==event&&typeof(observer[1])=='function')
observer[1](sender.getAttribute('name'),eventArgs);});},_showPopupMenu:function(tabItem){var offset=Position.cumulativeOffset(tabItem);this.popupMenu.innerHTML='';try{var tabName=tabItem.getAttribute('name');var dataItems=this.dataItems[tabName];var tabKey=tabItem.getAttribute('key');for(var i=0,item;item=dataItems[i];i++){if(item[this.options.dataKey]==tabKey&&tabItem.getAttribute('static')!='static')
continue;var li=document.createElement("li");var a=document.createElement("a");if(item.picto){var picto=document.createElement("img");picto.src=item.picto;picto.style.marginRight="4px";picto.style.marginBottom="-2px";a.appendChild(picto);}
else if(item.icon){var icon=document.createElement("img");icon.src=item.icon;icon.style.marginRight="4px";icon.style.marginBottom="-2px";a.appendChild(icon);}
a.href=(item.htmlUrl||"javascript:void(0)");a.setAttribute('context',tabName);a.appendChild(document.createTextNode(item.text));a.setAttribute("key",item[this.options.dataKey]);if(!this.options.extendedAction&&(dataItems.length-1)==i){Element.addClassName(a,'last');}
a.onclick=this.eventPopupMenuClicked.bindAsEventListener(this);li.appendChild(a);this.popupMenu.appendChild(li);}
if(this.options.extendedAction){var li=document.createElement("li");var a=document.createElement("a");a.href="javascript:void(0)";Element.addClassName(a,'action');a.setAttribute('context',tabName);a.appendChild(document.createTextNode(this.options.extendedAction));a.onclick=this.eventExtendedActionClicked.bindAsEventListener(this);li.appendChild(a);this.popupMenu.appendChild(li);}}
catch(e){}
var tabDimensions=Element.getDimensions(tabItem);var delta=0;this.popupMenu.style.left=(offset[0]+delta)+'px';this.popupMenu.style.top=(offset[1]+delta+tabDimensions.height)+'px';this.popupMenu.style.width="auto";var menuWidth=Element.getDimensions(this.popupMenu).width;if(menuWidth<tabDimensions.width){var delta=12;if(document.all)delta=11;this.popupMenu.style.width=tabDimensions.width-delta+"px";}
Element.show(this.popupMenu);var drops=$(this.tabList).getElementsByClassName("dropped");$A(drops).each(function(el){Element.removeClassName(el,"dropped");});Element.addClassName(tabItem,'dropped');},eventPopupMenuClicked:function(e){var sender=Event.findElement(e,"A");var tabName=sender.getAttribute('context');var tabItem=this.getTab(tabName);if(tabItem.getAttribute('static')!='static'){var dataKey=this.options.dataKey;var dataItem=this.dataItems[tabName].detect(function(el){return el[dataKey]==sender.getAttribute('key')});tabItem.getElementsByTagName("span")[0].innerHTML=dataItem.text;if(dataItem.picto){tabItem.getElementsByTagName("img")[0].src=dataItem.picto;}
else if(dataItem.icon){tabItem.getElementsByTagName("img")[0].src=dataItem.icon;}}
tabItem.setAttribute("key",sender.getAttribute('key'));this._notify('activeTabChange');this.selectTab(tabItem);this.hidePopupMenu();Event.stop(e);return false;},selectKey:function(name,key,select){var tabItem=this.getTab(name);var dataItem=null;var dataKey=this.options.dataKey;if(typeof(this.dataItems[name].detect)=='function'){dataItem=this.dataItems[name].detect(function(el){return el[dataKey]==key;});}
if(dataItem){tabItem.getElementsByTagName("span")[0].innerHTML=dataItem.text;tabItem.setAttribute("key",key);if(dataItem.icon){tabItem.getElementsByTagName("img")[0].src=dataItem.icon;}
if(select===undefined||select){this.selectTab(tabItem);}
if(select===undefined||select){this.selectTab(tabItem);}}},hidePopupMenu:function(e){if(!this.popupMenu)
return false;if(e&&Position.within(this.popupMenu,Event.pointerX(e),Event.pointerY(e))){Event.stop(e);return false;}
Element.hide(this.popupMenu);var drops=$(this.tabList).getElementsByClassName("dropped");$A(drops).each(function(el){Element.removeClassName(el,"dropped");});},createTabContent:function(name,index){var tabContent=document.createElement("div");if(this.options.softPadding){if(document.all)tabContent.style.padding="3px 3px 3px 3px";else tabContent.style.padding="6px 3px 3px 3px";}
tabContent.className=this.options.tabContentClass;tabContent.setAttribute("name",name);tabContent.innerHTML="Loading ...";this.tabSet.appendChild(tabContent);if(!this.contentArray)this.contentArray=[];this.contentArray.push(tabContent);tabContent.setAttribute("tabIndex",this.contentArray.length-1);},restoreState:function(module){var data=module.dataObj.data;if(typeof data.miniTabViewState!='undefined'){var state=data.miniTabViewState.parseJSON();if(state&&typeof state.selectedKey=='string'){this.selectKey(state.selectedKey);return;}
if(state&&typeof state.selectedTab=='string'){this.selectTab(state.selectedTab);return;}}
this.selectTab(0);},saveState:function(module){var jsonViewState=null;var selectedKey=this.selectedTab.getAttribute('key');if(typeof selectedKey=='string'){jsonViewState='{"selectedKey": "'+selectedKey+'"}';}
else{jsonViewState='{"selectedTab": "'+this.selectedTab.getAttribute('name')+'"}';}
if(jsonViewState&&jsonViewState!=module.dataObj.data.miniTabViewState){module.dataObj.data.miniTabViewState=jsonViewState;module.save();}},destroy:function(){Event.stopObserving(document,'mousedown',this.hidePopupMenu);}}
var OWA={Permit:{isAdmin:isMyBlog()}}
UWA.Module=function(m_data,m_content,m_edit,w_path){this.initVars(m_data,m_content,m_edit);}
UWA.Module.prototype.initVars=function(m_data,m_content,m_edit){if(typeof(m_data)=="string"){if(m_data.length>0){this.data=eval("("+m_data+")");}else{this.data={};}}else{this.data=m_data;}
if(typeof(this.data.ref)!="object")this.data.ref={};this.contentEle=m_content;this.editEle=m_edit;this.wrapper=null;this.body=null;this.widget=null;this.ref=null;this.refValue=null;this.refForm=null;this.timer=null;this.autoRefresh=0;this.refTimer=null;this.isPrivate=false;this.isEditing=false;this.widget=null;}
UWA.Module.prototype.isSetTest=function(){return this.data&&this.data.testpath&&(this.data.testpath.length>0);}
UWA.Module.prototype.isNormal=function(){return this.data&&this.data.path&&(this.data.path.length>0);}
UWA.Module.prototype.onCloseEdit=function(){this.isEditing=false;}
UWA.Module.prototype.gettedWrapper=function(wrapper){this.wrapper=wrapper;if(!this.wrapper){if(!this.isNormal())this.data.testpath=null;this.contentEle.innerHTML='对不起，此模块不可用！';return;}
if(this.wrapper.isPrivate||this.isPrivate){if(!isMyBlog()){return this.notShow();}}
this.edit=null;this.refresh=null;this.ref=null;this.refValue=null;this.refForm=null;this.contentEle.innerHTML='<div class="uwa_widget_'+this.wrapper.classId+'"></div>';this.body=UWA.$element(this.contentEle.firstChild);this.initWidget();var autoRefresh=this.wrapper.getIntro().autoRefresh;if(typeof(autoRefresh)=="number"&&autoRefresh>0){this.autoRefresh=autoRefresh*1000;this.setTimer();}
if(this.loaded)this.loaded();}
UWA.Module.prototype.setTimer=function(){if(this.autoRefresh&&this.refresh){this.timer=window.setTimeout(this.refresh.bind(this),this.autoRefresh);}}
UWA.Module.prototype.clearTimer=function(){if(this.timer){window.clearTimeout(this.timer);this.timer=null;}}
UWA.Module.prototype.notShow=function(){this.contentEle.innerHTML='此模块为私有模块，只有博主可用';if(this.loaded)this.loaded();return false;}
UWA.Module.prototype.initWidget=function(){this.widget=new UWA.Widget();this.widget.body=UWA.$element(this.body);this.widget.getValue=this.getRef.bind(this);this.widget.setValue=this.setRef.bind(this);this.widget.setTitle=this.onSetTitle.bind(this);this.widget.setAutoRefresh=this.setAutoRefresh.bind(this);this.widget.log=this.log.bind(this);this.initRef();try{this.widget.initialize(this.wrapper.getIntro().title,this.wrapper.getBody(),this.wrapper.getScripts());}catch(e){this.log(e);}
var hadRefresh=false;var hadEdit=false;if(this.widget.onRefresh&&typeof(this.widget.onRefresh)=="function"){hadRefresh=true;this.refresh=this._refresh;}
if(this.isNormal()){for(var i=0;i<this.ref.length;i++){if(this.ref[i].type=="hidden")continue;hadEdit=true;break;}}else{hadEdit=true;}
if(hadEdit)this.edit=this._edit;if(hadRefresh||hadEdit)this.resetControls();if(this.widget.onLoad&&typeof(this.widget.onLoad)=="function"){try{this.widget.onLoad();}catch(e){this.log(e);}}
var ico=this.wrapper.getIntro().icon;if(ico&&ico.length>0){this.setIco(ico);}}
UWA.Module.prototype.onSetTitle=function(title){if(typeof(title)=="string"&&title.length>0){if(title.length>8){var PatSWord=/^[\x00-\xff]+$/;var length=0;for(var i=0;i<title.length;i++){var char=title.charAt(i);if(PatSWord.test(char)){length+=1;}
else{length+=2;}
if(length>16)break;}
title=title.substr(0,i);}
this.setTitle(title,true);}}
UWA.Module.prototype.initRef=function(){this.ref=this.wrapper.getPreferences();}
UWA.Module.prototype.onSubmit=function(){if(!this.isNormal()&&!this.isSetTest()){var path=this.getRef("testpath");if(typeof(path)=="string"&&path.length>0&&path.trim().length>0){var data={testpath:path.trim()};this.endSave=function(){this.data=data;if(!this.data.ref)this.data.ref={};this.initialize();this.endSave=null;}
this.save(data);}
this.isEditing=false;}else{var refData=this.data.ref;if(this.refForm){for(var i=0;i<this.ref.length;i++){var refNow=this.ref[i];if(refNow.type=="hidden")continue;switch(refNow.type){case"text":case"password":var formValue=this.refForm[refNow.name].value;if(typeof(formValue)=="undefined"||formValue==null||formValue==""||formValue==refNow.defaultValue){refData[refNow.name]=undefined;}else{refData[refNow.name]=formValue;}
break;case"boolean":var formValue=this.refForm[refNow.name].checked.toString();if(formValue!=refNow.defaultValue){refData[refNow.name]=formValue;}else{refData[refNow.name]=undefined;}
break;case"range":case"list":var formValue=this.refForm[refNow.name].value;refData[refNow.name]=formValue;break;}}}
this.save(this.data);this.isEditing=false;if(this.refresh)this.refresh();}
return false;}
UWA.Module.prototype.setAutoRefresh=function(delay){this.clearTimer();if(typeof(delay)!="number"){delay=0;try{delay=parseInt(delay);}catch(e){this.log(e);}}
if(delay>0){this.autoRefresh=delay*1000;this.setTimer();}}
UWA.Module.prototype.getRef=function(name){if(this.ref[name]){if(this.isEditing&&this.refForm&&this.ref[name].type!="hidden"){switch(this.ref[name].type){case"boolean":return this.refForm[name].checked.toString();break;default:return this.refForm[name].value;break;}}else{var value=typeof(this.data.ref[name])=='undefined'?this.ref[name].defaultValue:this.data.ref[name];return typeof(value)=="undefined"?value:value.toString();}}else{var e=new ReferenceError('不存在属性设置项"'+name+'"');this.log(e);}}
UWA.Module.prototype.setRef=function(name,value){if(this.ref[name]){this.data.ref[name]=typeof(value)=="undefined"?undefined:value.toString();if(this.refForm&&this.ref[name].type!="hidden"){if(this.ref[name].type=="boolean"){this.refForm[name].checked=value=="true";}else{this.refForm[name].value=value;}}
if(this.refTimer==null){this.refTimer=window.setTimeout(this.setRefNow.bind(this),200);}}else{var e=new ReferenceError('不存在属性设置项"'+name+'"');this.log(e);}}
UWA.Module.prototype.setRefNow=function(){this.save(this.data);this.refTimer=null;}
UWA.Module.prototype.log=function(obj){if(this.wrapper.getIntro().debugMode){UWA.log(obj);}}
UWA.Module.prototype.initialize=function(){this.contentEle.innerHTML='正在加载...';if(this.isNormal()){UWA.WidgetLib.getWidget(this.data.path,this.gettedWrapper.bind(this),true);}else{this.isPrivate=true;if(this.isSetTest()){UWA.WidgetLib.getWidget(this.data.testpath,this.gettedWrapper.bind(this),false);}else{var scriptStr=''+'widget.onLoad = function() {'+'widget.setBody("本模块可以用来测试一个标准的Sohu Open Widget。<br />请点击此模块右上角的“设置”，填入您要测试的Widget地址。");'+'}';var obj={intro:{debugMode:true},scripts:[scriptStr],refs:[{type:"text",label:"地址",name:"testpath"}],body:""}
var wrapper=UWA.WidgetWrapper.getFromObj(obj);this.gettedWrapper(wrapper);}}}
UWA.Module.prototype.destroy=function(){if(this.refTimer)this.setRefNow();this.clearTimer();this.widget=null;this.wrapper=null;this.body=null;this.ref=null;this.contentEle.innerHTML="";}
UWA.Module.prototype._refresh=function(){if(this.widget){this.clearTimer();try{this.widget.onRefresh();}catch(e){this.log(e);}
this.setTimer();if(this.loaded)this.loaded();}}
UWA.Module.prototype.addMe=function(){if(this.isNormal()){window.open('http://blog.sohu.com/manage/module.do?m=preview&url='+encodeURIComponent(this.data.path));return true;}
return false;}
UWA.Module.prototype._edit=function(){this.isEditing=true;if(this.widget){if(!this.refForm){var str='<form onsubmit="return false"><table border="0" cellpadding="2" cellspacing="0">';var rowIndex=-1;if(!this.isNormal()){str+='<tr><td width="45px">&nbsp;</td><td>此模块为"测试模块"</td></tr>';rowIndex++;}
var onchanges=[];var showCount=0;var dataRef=this.data.ref;for(var i=0;i<this.ref.length;i++){var refNow=this.ref[i];if(refNow.type=="hidden")continue;showCount++;rowIndex++;str+='<tr><td width="45px">'+refNow.label+':</td><td>';var refName=refNow.name;var refValue=(typeof(dataRef[refName])=="undefined")?refNow.defaultValue:dataRef[refName];switch(refNow.type){case"text":str+='<input type="text" class="text" name="'+refName+'" '+(typeof(refValue)=="string"?(' value="'+refValue+'" '):'')+' />';break;case"boolean":str+='<input type="checkbox" name="'+refName+'" '+(refValue=="true"?(' checked="checked" '):'')+' />';if(refNow.onchange)onchanges.push(rowIndex);break;case"range":str+='<select class="text" name="'+refName+'">';var min=parseFloat(refNow.min);var max=parseFloat(refNow.max);var step=parseFloat(refNow.step);if(max>min){for(var j=min;j<=max;j+=step){str+='<option value="'+j+'" '+(refValue==j.toString()?' selected="selected" ':'')+'>'+j+'</option>';}}
str+='</select>';if(refNow.onchange)onchanges.push(rowIndex);break;case"list":str+='<select class="text" name="'+refName+'">';for(var j=0;j<refNow.options.length;j++){str+='<option value="'+refNow.options[j].value+'" '+((typeof(refValue)!="undefined"&&refValue==refNow.options[j].value)?' selected="selected" ':'')+'>'+refNow.options[j].label+'</option>';}
str+='</select>';if(refNow.onchange)onchanges.push(rowIndex);break;case"password":str+='<input type="password" class="text" name="'+refName+'" '+(typeof(refValue)=="string"?(' value="'+refValue+'" '):'')+' />';break;}
str+='</td></tr>';}
str+='<tr><td>&nbsp;</td><td><input type="submit" name="" value="'+App.Lang.save+'" class="button-submit" /></td></tr></table></form>';if(showCount==0){this.editEle.innerHTML='<table border="0" cellpadding="2" cellspacing="0"><tr><td width="45px">&nbsp;</td><td>此模块为"测试模块"</td></tr><tr><td width="45px">&nbsp;</td><td>此模块没有可设置项</td></tr></table>';}else{this.editEle.innerHTML=str;this.refForm=this.editEle.firstChild;var table=this.refForm.firstChild;if(onchanges.length>0&&this.refresh){for(var i=0;i<onchanges.length;i++){Event.observe(table.rows[onchanges[i]].cells[1].firstChild,"change",this.refresh.bind(this));}}
Event.observe(this.refForm,"submit",this.onSubmit.bind(this));}}}else{this.editEle.innerHTML='加载完成才能使用此功能';}}
var uwa_widget=UWA.Module;registerWidget("uwa_widget");